baseURL = 'https://indigente.github.io'
languageCode = 'pt-br'
title = 'Indigente'
theme = "ananke"
paginate = 50

summaryLength = 20

[params]
    recent_posts_number = 3
    mainSections = ["projetos", "eventos"]

[[menu.main]]
    name = "sobre"
    weight = -120
    identifier = "sobre"
    url = "/sobre/"
[[menu.main]]
    name = "eventos"
    weight = -110
    identifier = "eventos"
    url = "/eventos/"
[[menu.main]]
    name = "projetos"
    weight = -100
    url = "/projetos/"
[[menu.main]]
    name = "publicações"
    weight = -90
    url = "/publicacoes/"
[[menu.main]]
    name = "pessoas"
    weight = -80
    url = "/pessoas/"